### ISSUE TITLE
Restrict API access by IP

### ISSUE THREAD

**Issue by miki79** [servian/aws-auto-cleanup#78]
At the moment when you deploy the API, there is no security mechanism in place, so everybody that can access the API can change the whitelist and look at the resources.

A quick solution to block the access would be via IP restriction, so that the frontend web app wouldn't require any changes.

To restrict access by IP, it would be possible to use the resource policy for the API gateway and set it up via serverless with something like this

```yaml
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - ${self:custom.ipRange}
```
so the changes to serverless.yml in api directory would be like this

```yaml
custom:
  log_level: INFO # DEBUG for dev | INFO for prod
  region: ${opt:region, "ap-southeast-2"} # AWS deployment region
  manifest:
    output: ../web/src/serverless.manifest.json
    silent: true
  pythonRequirements:
    layer:
      name: ${self:service}-${self:provider.stage}-requirements
      compatibleRuntimes:
        - python3.8
    noDeploy:
      - boto
      - boto3
      - botocore
    slim: true
  ipRange: ${opt:ip, "0.0.0.0/0"} # overwrite via CLI "--ip 50.1.0.0/24"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "prod"} # overwrite via CLI "--stage dev"
  region: ${self:custom.region}
  profile: ${opt:profile, ""} # overwrite via CLI "--aws-profile saml"
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - ${self:custom.ipRange}
  apiGateway:
    minimumCompressionSize: 1024
```

**Comment by miki79** [comment]
I'm happy to create a PR, but I'd like to discuss how you prefer to setup the IP range

**Comment by mlevit** [comment]
Hey @miki79 thanks for the recommendation. I think the easiest way to secure the API is to make it private.

```
service: my-service
provider:
  name: aws
  apiGateway:
    apiKeys:
      - myFirstKey
functions:
  hello:
    events:
      - http:
          path: user/create
          method: get
          private: true
```

The private key is generated and needs to be passed in for each API request. The trick here is to pass that generated key to the web application during deployment. Are you able to look into this?
